/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a Google id_token for app JWTs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id_token: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh: string;
                    };
                };
            };
            responses: {
                /** @description New access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access?: string;
                        };
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current student's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "target_university": null,
                         *       "target_specialty": null,
                         *       "target_score": null,
                         *       "onboarding_completed": false,
                         *       "expected_scores": []
                         *     }
                         */
                        "application/json": components["schemas"]["StudentProfile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile / complete onboarding */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StudentProfileUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentProfile"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/profile/onboarding-options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options for the onboarding wizard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "universities": [
                         *         {
                         *           "id": 1,
                         *           "name": "Казахстанско-Британский Технический Университет",
                         *           "city": "Алматы",
                         *           "code": "KBTU",
                         *           "specialties": []
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "ЕНУ им. Гумилёва",
                         *           "city": "Астана",
                         *           "code": "ENU",
                         *           "specialties": []
                         *         },
                         *         {
                         *           "id": 3,
                         *           "name": "Назарбаев Университет",
                         *           "city": "Астана",
                         *           "code": "NU",
                         *           "specialties": []
                         *         },
                         *         {
                         *           "id": 4,
                         *           "name": "КазНУ им. аль-Фараби",
                         *           "city": "Алматы",
                         *           "code": "KazNU",
                         *           "specialties": []
                         *         }
                         *       ],
                         *       "specialties": [
                         *         {
                         *           "id": 11,
                         *           "university_id": 1,
                         *           "name": "Информационные системы",
                         *           "code": "6B06101",
                         *           "latest_threshold": 118
                         *         },
                         *         {
                         *           "id": 12,
                         *           "university_id": 1,
                         *           "name": "Компьютерная инженерия",
                         *           "code": "6B06102",
                         *           "latest_threshold": 125
                         *         },
                         *         {
                         *           "id": 21,
                         *           "university_id": 2,
                         *           "name": "Программная инженерия",
                         *           "code": "6B06201",
                         *           "latest_threshold": 115
                         *         },
                         *         {
                         *           "id": 22,
                         *           "university_id": 2,
                         *           "name": "Прикладная математика",
                         *           "code": "6B05402",
                         *           "latest_threshold": 110
                         *         },
                         *         {
                         *           "id": 31,
                         *           "university_id": 3,
                         *           "name": "Computer Science",
                         *           "code": "6B06301",
                         *           "latest_threshold": 132
                         *         },
                         *         {
                         *           "id": 32,
                         *           "university_id": 3,
                         *           "name": "Robotics",
                         *           "code": "6B06302",
                         *           "latest_threshold": 130
                         *         },
                         *         {
                         *           "id": 41,
                         *           "university_id": 4,
                         *           "name": "Математика",
                         *           "code": "6B05401",
                         *           "latest_threshold": 105
                         *         },
                         *         {
                         *           "id": 42,
                         *           "university_id": 4,
                         *           "name": "Информатика",
                         *           "code": "6B06103",
                         *           "latest_threshold": 112
                         *         }
                         *       ],
                         *       "subjects": [
                         *         "История Казахстана",
                         *         "Грамотность чтения",
                         *         "Математическая грамотность",
                         *         "Профильный предмет 1",
                         *         "Профильный предмет 2"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            universities?: components["schemas"]["University"][];
                            specialties?: components["schemas"]["Specialty"][];
                            /** @description Other ENT subjects the student estimates */
                            subjects?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List modules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Module"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Module detail with lessons */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModuleDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson detail (video + linked micro-test id) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesson"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test metadata (no answers revealed) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Test"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an attempt; returns questions WITHOUT correct flags */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        test_id: number;
                    };
                };
            };
            responses: {
                /** @description Attempt started */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptStart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/answer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit one answer. is_correct returned immediately for micro tests, null for mock. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        question_id: number;
                        option_id: number;
                    };
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description null for mock tests until finish */
                            is_correct?: boolean | null;
                            xp_awarded?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/finish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish attempt and compute score */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finished */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error review with correct answers and teacher explanations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptReview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-tag performance for radar / progress bars */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "tag": {
                         *           "id": 1,
                         *           "name": "Логарифмы",
                         *           "slug": "logarithms"
                         *         },
                         *         "correct": 4,
                         *         "total": 6,
                         *         "percent": 67
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 2,
                         *           "name": "Тригонометрия",
                         *           "slug": "trigonometry"
                         *         },
                         *         "correct": 2,
                         *         "total": 10,
                         *         "percent": 20
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 3,
                         *           "name": "Дроби",
                         *           "slug": "fractions"
                         *         },
                         *         "correct": 8,
                         *         "total": 10,
                         *         "percent": 80
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 4,
                         *           "name": "Производная",
                         *           "slug": "derivative"
                         *         },
                         *         "correct": 3,
                         *         "total": 8,
                         *         "percent": 38
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 5,
                         *           "name": "Геометрия",
                         *           "slug": "geometry"
                         *         },
                         *         "correct": 5,
                         *         "total": 7,
                         *         "percent": 71
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 6,
                         *           "name": "Уравнения",
                         *           "slug": "equations"
                         *         },
                         *         "correct": 9,
                         *         "total": 10,
                         *         "percent": 90
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["TagStat"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/recommendations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weak tags (<50%) with linked lessons to study */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "tag": {
                         *           "id": 2,
                         *           "name": "Тригонометрия",
                         *           "slug": "trigonometry"
                         *         },
                         *         "percent": 20,
                         *         "lessons": [
                         *           {
                         *             "id": 21,
                         *             "title": "Синусы и косинусы",
                         *             "order": 1,
                         *             "duration_sec": 420,
                         *             "completed": false
                         *           },
                         *           {
                         *             "id": 22,
                         *             "title": "Тригонометрические тождества",
                         *             "order": 2,
                         *             "duration_sec": 540,
                         *             "completed": false
                         *           }
                         *         ]
                         *       },
                         *       {
                         *         "tag": {
                         *           "id": 4,
                         *           "name": "Производная",
                         *           "slug": "derivative"
                         *         },
                         *         "percent": 38,
                         *         "lessons": [
                         *           {
                         *             "id": 41,
                         *             "title": "Понятие производной",
                         *             "order": 1,
                         *             "duration_sec": 360,
                         *             "completed": false
                         *           },
                         *           {
                         *             "id": 42,
                         *             "title": "Производная сложной функции",
                         *             "order": 2,
                         *             "duration_sec": 510,
                         *             "completed": false
                         *           }
                         *         ]
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Recommendation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/careers/universities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** University + specialty + threshold catalog */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["University"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/careers/calculate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predicted ENT score, qualifying grants, and goal gap
         * @description Uses the latest COMPLETED math mock attempt + the student's expected scores for other subjects (from profile). Returns qualifying specialties and, if a target is set, the gap and weakest-tag advice.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "predicted_score": 118,
                         *       "math_score": 48,
                         *       "other_subjects_total": 70,
                         *       "qualifying_grants": [
                         *         {
                         *           "university_name": "КазНУ им. аль-Фараби",
                         *           "specialty_name": "Математика",
                         *           "min_score": 105,
                         *           "margin": 13
                         *         },
                         *         {
                         *           "university_name": "ЕНУ им. Гумилёва",
                         *           "specialty_name": "Прикладная математика",
                         *           "min_score": 110,
                         *           "margin": 8
                         *         },
                         *         {
                         *           "university_name": "ЕНУ им. Гумилёва",
                         *           "specialty_name": "Программная инженерия",
                         *           "min_score": 115,
                         *           "margin": 3
                         *         },
                         *         {
                         *           "university_name": "КазНУ им. аль-Фараби",
                         *           "specialty_name": "Информатика",
                         *           "min_score": 112,
                         *           "margin": 6
                         *         }
                         *       ],
                         *       "goal": {
                         *         "target_score": 132,
                         *         "predicted_score": 118,
                         *         "gap": 14,
                         *         "weakest_tag": "Тригонометрия",
                         *         "advice": "До цели не хватает 14 — упор на Тригонометрию."
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GrantCalcResult"];
                    };
                };
                /** @description No completed math mock attempt yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** XP, level, and streak for the current student */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Gamification"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail?: string;
            code?: string;
        };
        AuthTokens: {
            access?: string;
            refresh?: string;
            user?: components["schemas"]["User"];
        };
        User: {
            id?: number;
            email?: string;
            first_name?: string;
            is_staff?: boolean;
            onboarding_completed?: boolean;
        };
        ExpectedScore: {
            subject?: string;
            score?: number;
        };
        StudentProfile: {
            target_university?: number | null;
            target_specialty?: number | null;
            target_score?: number | null;
            onboarding_completed?: boolean;
            expected_scores?: components["schemas"]["ExpectedScore"][];
        };
        StudentProfileUpdate: {
            target_university?: number | null;
            target_specialty?: number | null;
            target_score?: number | null;
            expected_scores?: components["schemas"]["ExpectedScore"][];
        };
        Tag: {
            id?: number;
            name?: string;
            slug?: string;
        };
        Module: {
            id?: number;
            title?: string;
            slug?: string;
            order?: number;
            /** @enum {string} */
            subject?: "math_literacy" | "profile_math";
            lesson_count?: number;
        };
        ModuleDetail: components["schemas"]["Module"] & {
            lessons?: components["schemas"]["LessonSummary"][];
        };
        LessonSummary: {
            id?: number;
            title?: string;
            order?: number;
            duration_sec?: number;
            completed?: boolean;
        };
        Lesson: {
            id?: number;
            title?: string;
            description?: string;
            video_url?: string;
            /** @enum {string} */
            video_provider?: "youtube" | "vimeo";
            duration_sec?: number;
            micro_test_id?: number | null;
        };
        /** @description Option shape during a test — never reveals correctness */
        AnswerOptionPublic: {
            id?: number;
            text?: string;
        };
        QuestionPublic: {
            id?: number;
            text?: string;
            image?: string | null;
            options?: components["schemas"]["AnswerOptionPublic"][];
        };
        Test: {
            id?: number;
            /** @enum {string} */
            type?: "micro" | "mock";
            title?: string;
            time_limit_sec?: number | null;
            question_count?: number;
        };
        AttemptStart: {
            attempt_id?: number;
            test?: components["schemas"]["Test"];
            /** Format: date-time */
            started_at?: string;
            questions?: components["schemas"]["QuestionPublic"][];
        };
        AttemptResult: {
            attempt_id?: number;
            /** @description math score for this attempt */
            score?: number;
            correct_count?: number;
            total_count?: number;
            /** Format: date-time */
            finished_at?: string;
        };
        AttemptReviewItem: {
            question_id?: number;
            question_text?: string;
            selected_option_id?: number | null;
            correct_option_id?: number;
            is_correct?: boolean;
            /** @description teacher-written solution */
            explanation?: string;
            options?: {
                id?: number;
                text?: string;
                is_correct?: boolean;
            }[];
        };
        AttemptReview: {
            attempt_id?: number;
            score?: number;
            items?: components["schemas"]["AttemptReviewItem"][];
        };
        TagStat: {
            tag?: components["schemas"]["Tag"];
            correct?: number;
            total?: number;
            /** @description 0-100 */
            percent?: number;
        };
        Recommendation: {
            tag?: components["schemas"]["Tag"];
            percent?: number;
            lessons?: components["schemas"]["LessonSummary"][];
        };
        University: {
            id?: number;
            name?: string;
            city?: string;
            code?: string;
            specialties?: components["schemas"]["Specialty"][];
        };
        Specialty: {
            id?: number;
            university_id?: number;
            name?: string;
            code?: string;
            latest_threshold?: number | null;
        };
        QualifyingGrant: {
            university_name?: string;
            specialty_name?: string;
            min_score?: number;
            /** @description predicted - min_score */
            margin?: number;
        };
        GoalTracker: {
            target_score?: number;
            predicted_score?: number;
            /** @description target - predicted; <=0 means reached */
            gap?: number;
            weakest_tag?: string | null;
            /** @description e.g. "До цели не хватает 20 — упор на Тригонометрию" */
            advice?: string;
        };
        GrantCalcResult: {
            predicted_score?: number;
            math_score?: number;
            other_subjects_total?: number;
            qualifying_grants?: components["schemas"]["QualifyingGrant"][];
            goal?: components["schemas"]["GoalTracker"];
        };
        /**
         * @example {
         *       "total_xp": 1240,
         *       "level_code": "znatok",
         *       "level_label": "Знаток",
         *       "xp_to_next_level": 3760,
         *       "streak": {
         *         "current": 7,
         *         "longest": 15,
         *         "active_today": true
         *       }
         *     }
         */
        Gamification: {
            total_xp?: number;
            /** @description e.g. znatok */
            level_code?: string;
            level_label?: string;
            xp_to_next_level?: number;
            streak?: {
                current?: number;
                longest?: number;
                active_today?: boolean;
            };
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
